# $Id: Makefile,v 1.2 2000-05-28 13:00:35 unix01 Exp $
###############################################
LOCALDOCDIR=Doc

################################################



clean:
	\rm -f *.html *.css  *~ package-list
	\rm -f ./absyn/*.html
	rmdir ./absyn

