# $Id: Makefile,v 1.3 2000-05-28 15:12:40 unix01 Exp $
###############################################
LOCALDOCDIR=Doc

################################################



clean:
	\rm -f *.html *.css  *~ package-list
	\rm -f ./absynt/*.html
	rmdir ./absynt

