########################################################
## $Id: Makefile,v 1.1 2000-05-28 15:00:31 unix01 Exp $
########################################################


WEBDIR = /home/info/www/inf/deRoever/SS00/Java/Mist/Prototyp

clean:
	rm -f *.aux *.log *.dvi *.ps *.bbl *.blg *~

www:
	cp *.ps $(WEBDIR)