###############################################
LOCALDOCDIR=Doc
################################################



clean:
	\rm -f *.html *.css  *~ package-list
	\rm -f ./parser/*.html
	rmdir ./parser
