#----------------------------------------------------------------------
# local makefile
# $Id: Makefile,v 1.1 2000-06-27 08:41:58 unix01 Exp $
#----------------------------------------------------------------------


PACKAGEDIRS = absynt  utils editor gui checks1 parser\
	      modcheck simulator position1 position2

################################################

clean: ;
	rm -rf $(PACKAGEDIRS)
	rm -f *.html *.css package-list





