#----------------------------------------------------------------------
# local makefile
# $Id: Makefile,v 1.2 2000-06-27 08:46:00 unix01 Exp $
#----------------------------------------------------------------------


PACKAGEDIRS = absynt  utils editor gui checks1 parser\
	      modcheck simulator position1 position2

################################################

clean: ;
	rm -rf $(PACKAGEDIRS)
	rm -f *.html *.css package-list
	rm -f specification.txt





