# $Id: Makefile,v 1.1 2000-06-04 12:09:10 unix01 Exp $
###############################################
################################################



clean:
	\rm -f *.html *.css  *~ package-list
	\rm -f ./utils/*.html
	rmdir ./utils

