########################################################
## $Id: Makefile,v 1.1 2000-05-28 15:00:32 unix01 Exp $
########################################################


WWWDIR      = /home/info/www/inf/deRoever/SS00/Java/Mist

www:
	cp *.html  $(WWWDIR)
